nelmio_api_doc:
    documentation:
        info:
            title: Hackathon MarketPlace
            description: API para la Hackathon MarketPlace de It Academy. Esta API permite la autenticaci칩n mediante JWT y la gesti칩n de usuarios y de actividades.
            version: 1.0.0
            contact:
                name: Iv치n Legr치n
                email: ivanlegranbizarro@gmail.com
                url: https://github.com/ivanlegranbizarro
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []

    areas:
        path_patterns: [ ^/api/(?!doc$|activity/(import|export|create)$).*$ ]
